env:
  TERM: xterm-256color

font:
  normal:
    family: Inconsolata
    style: Regular
  bold:
    family: Inconsolata
    style: Bold
  size: 17.0

colors:
  primary:
    background: '0xf1efee'
    foreground: '0x68615e'
  cursor:
    text: '0xf1efee'
    cursor: '0x68615e'
  normal:
    black:   '0xf1efee'
    red:     '0xf22c40'
    green:   '0x7b9726'
    yellow:  '0xc38418'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x3d97b8'
    white:   '0x68615e'
  bright:
    black:   '0x9c9491'
    red:     '0xf22c40'
    green:   '0x7b9726'
    yellow:  '0xc38418'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x3d97b8'
    white:   '0x1b1918'
  indexed_colors:
    - { index: 16, color: '0xdf5320' }
    - { index: 17, color: '0xc33ff3' }
    - { index: 18, color: '0xe6e2e0' }
    - { index: 19, color: '0xa8a19f' }
    - { index: 20, color: '0x766e6b' }
    - { index: 21, color: '0x2c2421' }

bell:
  duration: 0

cursor:
  style:
    shape: Beam
    blinking: On
  blink_interval: 500
  unfocused_hollow: true

shell:
  program: zsh
  args:
    - --login

working_directory: /Users/ttaylorr

hints:
  enabled:
    - regex: "([0-9a-f]{40}([0-9a-f]{24})?)|([0-9a-f]{7,10})"
      action: copy
      mouse:
        enabled: true
      binding:
        key: S
        mods: control
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
