env:
  TERM: xterm-256color

font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  size: 15.0
  use_thin_strokes: true

bell:
  duration: 0

cursor:
  style: Beam
  unfocused_hollow: true
  shell:
    program: /usr/local/bin/zsh
    args:
      - --login

hints:
  enabled:
    - regex: "([0-9a-f]{40}([0-9a-f]{24})?)|([0-9a-f]{7,10})"
      action: copy
      mouse:
        enabled: true
      binding:
        key: S
        mods: control
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
      binding:
        key: S
        mods: control
