[general]
working_directory = "/Users/ttaylorr"
import = [
  "/Users/ttaylorr/.alacritty.d/themes/light.toml"
]

[bell]
duration = 0

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.normal]
family = "Inconsolata"
style = "Regular"

[[hints.enabled]]
action = "copy"
regex = "([0-9a-f]{40}([0-9a-f]{24})?)|([0-9a-f]{7,10})"

[hints.enabled.binding]
key = "S"
mods = "control"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[terminal.shell]
args = ["--login"]
program = "zsh"
