env:
  TERM: xterm-256color

font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  size: 15.0
  use_thin_strokes: true

bell:
  duration: 0

cursor:
  style: Beam
  unfocused_hollow: true
  shell:
    program: /usr/local/bin/zsh
    args:
      - --login
mouse:
  url:
    launcher:
      program: None
