#!/usr/bin/env bash
#
# Update all sub-modules for a given packname, defaulting to "ttaylorr".
#
# USAGE:
#   $ update_pack [packname]

main() {
  local packname="${1-ttaylorr}"

  parallel "\
    pushd {} >/dev/null
      git submodule update --init

      git checkout -q master
      git pull origin master
    popd >/dev/null" \
    ::: "$(list_submodules_in "vim/pack/$packname")"

  if [ -d "vim/pack/$packname/LanguageClient-neovim" ]; then
    (
      cd "vim/pack/$packname/LanguageClient-neovim"
      bash install.sh
    )
  fi
}

list_submodules_in() {
  local dir="$1"

  git submodule \
    | awk '{ print $2 }' \
    | grep -e "^$dir"
}

main;
