#!/bin/bash

set -e

function main() {
  old_branch=$(git name-rev HEAD 2> /dev/null | awk "{ print \$2 }")
  update_master
  sync_master
}

function update_master() {
  git checkout master
  git pull origin master
}

function sync_master() {
  git checkout $old_branch
  git rebase -i master
}

main
